// vue-pokedex/src/components/home-page/Navigation.vue
<script setup>
import { usePokemonStore } from "@/stores/pokemon";
import { ArrowLeftCircleIcon, ArrowRightCircleIcon } from "lucide-vue-next";
import { reactive } from "vue";

const pokemonStore = usePokemonStore();

const state = reactive({
  page: {
    type: String,
  },
  changePage: function (e) {
    e.preventDefault();
    console.log(state.page);
    pokemonStore.setPage(state.page);
    console.log(pokemonStore.currentPage);
  },
});
</script>

<template>
  <div class="flex items-center justify-center py-10">
    <button
      @click="pokemonStore.previousPage()"
      :disabled="!pokemonStore.previous"
      class="disabled:text-zinc-500"
    >
      <ArrowLeftCircleIcon class="size-10" />
    </button>
    <form @submit="(e) => state.changePage(e)">
      <input
        type="text"
        :placeholder="pokemonStore.currentPage"
        :value="pokemonStore.currentPage"
        @change="(e) => (state.page = e.target.value)"
      />
    </form>
    <span>/ {{ pokemonStore.totalPages }}</span>
    <button
      @click="pokemonStore.nextPage()"
      :disabled="!pokemonStore.next"
      class="disabled:text-zinc-500"
    >
      <ArrowRightCircleIcon class="size-10" />
    </button>
  </div>
</template>

// vite-react-pokedex/src/components/homePage/navigation.jsx
import { ArrowLeftIcon, ArrowRightIcon } from "lucide-react";
import { useContext, useState } from "react";
import { PokedexContext } from "../../context/pokemonContext";

export function Navigation() {
  const [pageNumber, setPageNumber] = useState(1);

  const { nextPage, previousPage, totalPages, offset, setOffset } =
    useContext(PokedexContext);

  function handleNextPage() {
    if (nextPage) {
      if (String(pageNumber).trim() === "") {
        setPageNumber(offset / 24 + 1);
        return;
      }

      setOffset(offset + 24);
      setPageNumber(pageNumber + 1);
    }
  }

  function handlePreviousPage() {
    if (previousPage) {
      if (String(pageNumber).trim() === "") {
        setPageNumber(offset / 24 + 1);
        return;
      }

      setOffset(offset - 24);
      setPageNumber(pageNumber - 1);
    }
  }

  function handleFormSubmit(e) {
    e.preventDefault();

    const regex = /^(?:[1-9]|[1-4][0-9]|5[0-5])$/;

    if (pageNumber > 55) {
      setPageNumber(55);
      setOffset(55 * 24 - 24);
      return;
    }

    if (pageNumber <= 0) {
      setPageNumber(1);
      setOffset(1 * 24 - 24);
      return;
    }

    if (regex.test(pageNumber)) {
      setPageNumber(Number(pageNumber));
      setOffset(Number(pageNumber) * 24 - 24);
    }
  }

  return (
    <div className="flex items-center justify-center py-10">
      <button
        onClick={handlePreviousPage}
        disabled={!previousPage}
        className="disabled:text-zinc-600"
      >
        <ArrowLeftIcon />
      </button>
      <form onSubmit={handleFormSubmit}>
        <input
          type="text"
          placeholder={pageNumber}
          className="w-8 placeholder:text-center p-1 rounded-md text-center"
          onChange={(e) => setPageNumber(e.target.value)}
          value={pageNumber}
        />
        <span>{` / ${Math.ceil(totalPages)}`}</span>
      </form>
      <button
        onClick={handleNextPage}
        disabled={!nextPage}
        className="disabled:text-zinc-600"
      >
        <ArrowRightIcon />
      </button>
    </div>
  );
}
